# Generated by Django 3.1.1 on 2020-10-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
