# Generated by Django 3.1.1 on 2020-10-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0003_auto_20201012_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
