# Generated by Django 3.1.1 on 2020-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0004_auto_20201012_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=2048, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=2048, null=True)),
                ('token_url', models.URLField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
