# Generated by Django 3.1.1 on 2020-11-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0005_providerpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='provider_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth_client.providerpart'),
        ),
    ]
