# Generated by Django 3.1.1 on 2021-03-08 20:45

from django.db import migrations


def forward(apps, schema_editor):
    UserToken = apps.get_model('oauth_client', 'UserToken')
    Integration = apps.get_model('oauth_client', 'Integration')

    endpoints = list(UserToken.objects.all()
                     .values_list('endpoint', flat=True)
                     .distinct())
    for endpoint in endpoints:
        integration = Integration.objects.create(endpoint=endpoint)
        UserToken.objects \
            .filter(endpoint=endpoint) \
            .update(integration=integration)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0008_auto_20210308_2035'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
