# Generated by Django 3.1.1 on 2021-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0009_auto_20210308_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='installation',
            field=models.BooleanField(default=False),
        ),
    ]
