# Generated by Django 3.1.1 on 2021-03-08 21:58

from django.db import migrations


def forward(apps, schema_editor):
    Integration = apps.get_model('oauth_client', 'Integration')

    integrations = Integration.objects.all()
    for integration in integrations:
        token = integration.usertoken_set.all().order_by('id').first()
        if token:
            token.installation = True
            token.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0010_usertoken_installation'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
