# Generated by Django 3.1.1 on 2021-03-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0015_auto_20210310_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='installation',
        ),
    ]
