# Generated by Django 3.1.1 on 2021-04-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0017_integration_is_installed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProviderPart',
            new_name='Provider',
        ),
    ]
