# Generated by Django 3.1.1 on 2021-05-07 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth_client', '0019_auto_20210429_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='provider_part',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='provider',
            name='authorization_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='preset',
            field=models.CharField(choices=[('bx24', 'Bitrix24'), ('amocrm', 'amoCRM'), ('custom', 'Custom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='token_url',
            field=models.URLField(blank=True, default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usertoken',
            unique_together={('user', 'provider', 'integration'), ('user', 'provider', 'endpoint')},
        ),
    ]
