# Generated by Django 3.1.1 on 2021-05-07 21:39
from django.conf import settings
from django.db import migrations


def forward(apps, schema_editor):
    Provider = apps.get_model('oauth_client', 'Provider')
    UserToken = apps.get_model('oauth_client', 'UserToken')

    for provider in Provider.objects.all():
        provider.slug = f'{provider.preset}/{provider.id}'
        provider.save()

    for preset, config in getattr(settings, 'OAUTH2_PROVIDERS', {}).items():
        if config:
            client_id = config['client_id']
            client_secret = config['client_secret']
            authorization_url = config.get('authorization_url', '')
            if callable(authorization_url):
                authorization_url = ''
            token_url = config.get('token_url', '')
            if callable(token_url):
                token_url = ''
            provider, _ = Provider.objects.get_or_create(
                name=preset,
                preset=preset,
                slug=preset,
                client_id=client_id,
                client_secret=client_secret,
                authorization_url=authorization_url,
                token_url=token_url,
            )
            UserToken.objects \
                .filter(provider__isnull=True, preset=preset) \
                .update(provider=provider)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0020_auto_20210507_2128'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
