# Generated by Django 3.1.1 on 2021-05-07 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0021_auto_20210507_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='preset',
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_client.provider'),
        ),
    ]
