# Generated by Django 3.1.1 on 2021-07-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0022_auto_20210507_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='refresh_lock_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
