# Generated by Django 3.2.5 on 2021-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0024_auto_20210727_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='install_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='install_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
