# Generated by Django 3.2.5 on 2021-07-29 07:09

from django.db import migrations
from django.utils import timezone


def forward(apps, schema_editor):
    Integration = apps.get_model('oauth_client', 'Integration')
    now = timezone.now()
    Integration.objects \
        .filter(is_installed=True) \
        .update(install_start=now, install_finish=now)


def backward(apps, schema_editor):
    Integration = apps.get_model('oauth_client', 'Integration')
    Integration.objects \
        .filter(install_finish__isnull=False) \
        .update(is_installed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0025_auto_20210729_0654'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
