# Generated by Django 3.2.5 on 2021-07-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0026_auto_20210729_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='is_installed',
        ),
    ]
