# Generated by Django 3.2.5 on 2021-07-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0027_remove_integration_is_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='app_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
