# Generated by Django 3.2.5 on 2021-12-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0029_fill_integration_app_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
