# Generated by Django 3.2.16 on 2022-11-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_client', '0030_auto_20211225_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
